stages:
  process_data:
    cmd: python scripts/process_data.py
    deps:
      - data/raw
      - scripts/process_data.py
    params:
      - process_data
    outs:
      - processed_data/stock_data.parquet

  train:
    cmd: python scripts/train.py
    deps:
      - processed_data/stock_data.parquet
      - scripts/train.py
    params:
      - train
    outs:
      - models/model.joblib
