# Parameters for data processing
process_data:
  raw_path: "data/raw"
  processed_path: "processed_data/stock_data.parquet"
  # Data version (v0 or v1)
  data_version: v0 

# Parameters for training
train:
  processed_path: "processed_data/stock_data.parquet"
  model_path: "models/model.joblib"
  test_size: 0.2
  random_state: 42
  # Basic model params
  n_estimators: 10
  max_depth: 5
